### ISSUE TITLE
Does not work for long messages

### ISSUE THREAD

**Issue by xanonid** [CosmicToast/bmq#1]
`base64` wraps after 76 characters per default. This breaks the assumption of one line per message.

Use the `-w 0` setting to fix this. 
See https://linux.die.net/man/1/base64 .

**Comment by CosmicToast** [comment]
The implementation of base64 I am/was working with doesn't wrap at all (i.e `seq 1 99999 | base64 | wc -l` prints 1). This project was mostly meant for educational purposes ("what is an MQ", "what is a rollback journal", "what is a WAL", "how do I avoid corruption") rather than serious use.
I'm going to simply document this in the README in a "gotchas" section.
